all:
  urls:
    include: []
    variables:
      editRow: emailTemplates/edit
      showRow: emailTemplates/edit
      save: @emailtemplates?action=save
      deleteAction:  @emailtemplates?action=delete