<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('email_template', 'subject', 'string', '100');
    }

    public function down()
    {
        $this->removeColumn('email_template', 'subject');
    }
}