<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('customer', 'series_id', 'integer', '8', array(
             ));        
    }

    public function down()
    {
        $this->removeColumn('customer', 'series_id');        
    }
}